server:
  port: 8099  #端口
  tomcat:
    uri-encoding: UTF-8   #服务编码
spring:
  application:
    name: china-mobile-ai
  ai:
    openai: #openai配置
      api-key: ${OPENAI_API_KEY}
      base-url: https://api.openai.com
      chat:
        options:
          model: gpt-3.5-turbo #模型名称
      embedding:
        options:
          model: text-embedding-3-small

logging:
  level:
    org:
      springframework:
        ai:
          chat:
            client:
              advisor: DEBUG
